src/objects/Question_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Code__c</fullName>
        <label>Answer Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Question to which answers are related</description>
        <label>Parent Question</label>
        <referenceTo>Question_Answer__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questions_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Solution</label>
        <referenceTo>Question_Answer__c</referenceTo>
        <relationshipLabel>Solution Keys</relationshipLabel>
        <relationshipName>Solution_Key</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session Name</label>
        <referenceTo>Question_Answer__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Key_2__c</fullName>
        <label>Solution Key 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question &amp; Answer</label>
    <nameField>
        <displayFormat>QA-{0000000}</displayFormat>
        <label>Question &amp; Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions &amp; Answers</pluralLabel>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/azqa_setup.cls
public with sharing class azqa_setup{
	public Question_Answer__c theRecord{get;set;}
	public string key{get;set;}
	public azqa_setup(){
	
	}
	
	public azqa_setup(ApexPages.StandardController con){
		theRecord = (Question_Answer__c) con.getRecord();
	}
	
	public list<Question_Answer__c> getQuestions(){
		return [Select Q.Id,Q.Name,Q.Session_Name__c, Q.RecordType.Name, Q.Text__c, ( Select Id,Name, Answer_Code__c, Text__c from Questions_Answers__r order by Answer_Code__c) from Question_Answer__c Q WHERE Q.RecordType.Name = 'question' AND session_name__c = : theRecord.parent_solution__r.Session_Name__c ORDER BY  name];	
	}
	
	public pagereference updateKey(){
		system.debug('\n\n UPDATE KEY ' + key);
		therecord.Solution_Key_2__c = key;
		update theRecord;
		return null;
	}
	
}